[package]
name = "rusttab"
version = "0.0.2"
edition = "2021"
authors = ["Jan Malec jan.malec@ijs.si"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3.5"